"""add_leads_and_google_sheets

Revision ID: f9f693d77590
Revises: a0eaa83f98e2
Create Date: 2026-04-30 17:11:19.507469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f9f693d77590'
down_revision: Union[str, Sequence[str], None] = 'a0eaa83f98e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hotel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('guest_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('guest_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('guest_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('room_type_preference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('check_in', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('check_out', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('num_adults', sa.Integer(), nullable=False),
    sa.Column('num_children', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ai_conversation_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_hotel_id'), 'leads', ['hotel_id'], unique=False)
    op.add_column('integration_settings', sa.Column('google_sheet_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integration_settings', 'google_sheet_url')
    op.drop_index(op.f('ix_leads_hotel_id'), table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
