"""add_ai_model_and_url_to_settings

Revision ID: 08f1ec9309de
Revises: 9aac29c6dd7f
Create Date: 2026-04-30 17:42:59.302923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '08f1ec9309de'
down_revision: Union[str, Sequence[str], None] = '9aac29c6dd7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integration_settings', sa.Column('ai_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('integration_settings', sa.Column('ai_base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integration_settings', 'ai_base_url')
    op.drop_column('integration_settings', 'ai_model')
    # ### end Alembic commands ###
