"""add_ai_model_to_hotel

Revision ID: 45e4a7ec2367
Revises: 08f1ec9309de
Create Date: 2026-04-30 18:27:52.719720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '45e4a7ec2367'
down_revision: Union[str, Sequence[str], None] = '08f1ec9309de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('ai_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('hotels', sa.Column('ai_base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotels', 'ai_base_url')
    op.drop_column('hotels', 'ai_model')
    # ### end Alembic commands ###
