"""add_ai_fields_to_hotel

Revision ID: 9aac29c6dd7f
Revises: f9f693d77590
Create Date: 2026-04-30 17:36:11.924005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aac29c6dd7f'
down_revision: Union[str, Sequence[str], None] = 'f9f693d77590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
