"""add widget layout and logo to integration settings

Revision ID: 517bb6e1d3fb
Revises: 45e4a7ec2367
Create Date: 2026-05-04 18:13:50.331020

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '517bb6e1d3fb'
down_revision: Union[str, Sequence[str], None] = '45e4a7ec2367'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # We must provide a default value for existing rows when adding a non-nullable column
    op.add_column('integration_settings', sa.Column('widget_layout', sa.String(), nullable=False, server_default='modern'))
    op.add_column('integration_settings', sa.Column('widget_logo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integration_settings', 'widget_logo_url')
    op.drop_column('integration_settings', 'widget_layout')
    # ### end Alembic commands ###
